### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by mainmind83**
Spanish gui v2

### CODE REVIEW

**Comment by KipK** [comment]
Thanks for this. Can you also edit the i18n.js and add the es language there ? 

`register("es", () => import("./i18n/es.json"))`

**Comment by mainmind83** [comment]
I didn't see the list of available languages, it's already added!

**Comment by KipK** [comment]
Seems your json file have problem. The checks have failed

```
 Failed to parse JSON file.
file: /home/runner/work/openevse-gui-v2/openevse-gui-v2/src/lib/i18n/es.json
error during build:
RollupError: Failed to parse JSON file.
```

**Comment by mainmind83** [comment]
Sorry @KipK, copy/paste fixed ;D

**Pull request merged**
